ci: Support running cross tests for `x86_64-unknown-linux-gnu`

diff --git a/ci/docker/static/runner b/ci/docker/static/runner
--- a/ci/docker/static/runner
+++ b/ci/docker/static/runner
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+export QEMU_SET_ENV=LD_PRELOAD=$TARGET_LD_PRELOAD
+
 INFO=$(file $1)
 
 echo "$INFO" | grep -q "ARM aarch64"
@@ -20,4 +22,11 @@ if [[ "$?" -eq "0" ]]; then
     exec qemu-mips64 "$@"
 fi
 
+echo "$INFO" | grep -q "x86-64"
+if [[ "$?" -eq "0" ]]; then
+    export QEMU_LD_PREFIX=/
+    exec qemu-x86_64 "$@"
+fi
+
+echo "ERROR: Unknown architecture!"
 exit 1
